### ISSUE TITLE
Can't use

### ISSUE THREAD

**Issue by manhduonghn** [slashtechno/cloudflare-gateway-adblocking#8]
I installed cloudflare-gateway-adblocking on pypi but when I use command cloudflare-gateway-adblocking --account-id <my account id> , it said Error

**Comment by slashtechno** [comment]
> I installed cloudflare-gateway-adblocking on pypi but when I use command cloudflare-gateway-adblocking --account-id <my account id> , it said Error 

What error are you receiving?
In addition to your account ID, you need to specify your access token. 

Also, you need to use a subcommand. I assume you're trying to create the ad blocking rules. For this, you need to run `cloudflare-gateway-adblocking upload`, not just `cloudflare-gateway-adblocking`.

**Comment by manhduonghn** [comment]
Only use `cloudflare-gateway-adblocking upload` ? No need set `cloudflare-gateway-adblocking --account-id`

**Comment by slashtechno** [comment]
> Only use `cloudflare-gateway-adblocking upload` ? No need set `cloudflare-gateway-adblocking --account-id`

You still need to set your account ID and token. This can be done either with command-line flags, environment variables, or a `.env` file

**Comment by slashtechno** [comment]
Considering you closed the issue, is it working now?

**Comment by manhduonghn** [comment]
I try to run on termux and Github codespace and it not work. Can't add account id

**Comment by slashtechno** [comment]
What error are you encountering?

**Comment by manhduonghn** [comment]
I was delete it but I try 7 times,it still fail when I command `cloudflare-gateway-adblocking --account-id`

**Comment by slashtechno** [comment]
In that case, you need to use the `delete` subcommand. You're also missing a Cloudflare token.

Your command should look like this:
`cloudflare-gateway-adblocking --account-id <account ID> --token <token> delete`

**Comment by slashtechno** [comment]
Since you marked it as closed, did you resolve the issue?

**Comment by manhduonghn** [comment]
I will try it tomorrow

**Comment by slashtechno** [comment]
Okay, please leave the issue open for now. Closing the issue marks it as completed by default.

**Comment by manhduonghn** [comment]
![Screenshot_2023-08-13-09-05-11-215_com termux](https://github.com/slashtechno/cloudflare-gateway-adblocking/assets/29990924/6e9a0c1d-6a38-47f9-9a83-a56f2bec8a3e)

**Comment by manhduonghn** [comment]
![Screenshot_2023-08-13-09-09-31-941_com termux](https://github.com/slashtechno/cloudflare-gateway-adblocking/assets/29990924/109a09a8-5ae2-4285-a3bf-49ef389a325a)
How to do it? I use Termux

**Comment by manhduonghn** [comment]
#

![IMG_20230813_091336](https://github.com/slashtechno/cloudflare-gateway-adblocking/assets/29990924/79817b5c-3da8-4951-a55a-0059d3a14811)
How to do that? I use Termux. Thanks

**Comment by slashtechno** [comment]
> 
> #
> 
> ![IMG_20230813_091336](https://github.com/slashtechno/cloudflare-gateway-adblocking/assets/29990924/79817b5c-3da8-4951-a55a-0059d3a14811)
> How to do that? I use Termux. Thanks

To create the ad-block policy, you need to specify where your blocklist file/directory is with `--blocklists <path>`. This error is being raised as you have not specified a filepath which exists, and `./blocklists` also doesn't exist.

**Comment by manhduonghn** [comment]
Still unknown to use. So sorry

**Comment by slashtechno** [comment]
> Still unknown to use. So sorry

You need to download (or create) a blocklist in the format of a hosts file, and then specify the path to that file with `--blocklists`.

**Comment by manhduonghn** [comment]
Can I do it with my android phone?

**Comment by slashtechno** [comment]
> Can I do it with my android phone?  

Using Termux, you should be able to.

**Comment by manhduonghn** [comment]
`cloudflare-gateway-adblocking --account-id () --token () upload --blocklists ./storage/emulated/0/Download/hosts.txt` not work

**Comment by manhduonghn** [comment]
I think  you make Github Action to run code is better. Everyone can do that

**Comment by slashtechno** [comment]
> ./storage/emulated/0/Download/hosts.txt

I think this should be `/storage/emulated/0/Download/hosts.txt` without the `.` before `/` since this isn't a relative path.

**Comment by slashtechno** [comment]
> I think you make Github Action to run code is better. Everyone can do that

Github actions is meant more for CI/CD, which this is not.

**Comment by manhduonghn** [comment]
![Screenshot_2023-08-13-23-08-15-567_com alif ide python](https://github.com/slashtechno/cloudflare-gateway-adblocking/assets/29990924/1ed9d468-c972-491f-8998-140ab98776a8)
It said that

**Comment by manhduonghn** [comment]
![IMG_20230814_050600](https://github.com/slashtechno/cloudflare-gateway-adblocking/assets/29990924/ba9a812f-4016-45c1-bd37-301a8d50675b)
It said that

**Comment by slashtechno** [comment]
> ![IMG_20230814_050600](https://github.com/slashtechno/cloudflare-gateway-adblocking/assets/29990924/ba9a812f-4016-45c1-bd37-301a8d50675b)
> It said that

What scopes did you give to your token when generating it?

Make sure you're using the right account ID as well

**Comment by manhduonghn** [comment]
Yes, I use right ID user and my token is full permissions

**Comment by manhduonghn** [comment]
![Screenshot_2023-08-14-05-24-43-314_org triple banana](https://github.com/slashtechno/cloudflare-gateway-adblocking/assets/29990924/250195c6-5a79-4635-ab85-2740396bbce6)
This token works when I use your tool

**Comment by slashtechno** [comment]
> Yes, I use right ID user and my token is full access. 

I think the only thing which can cause that is incorrect credentials.  

I'm not familiar with Cloudflare full access tokens. This is my token configuration:  
![Screenshot_20230813-182556.png](https://github.com/slashtechno/cloudflare-gateway-adblocking/assets/77907286/8c31f156-ee6d-4a69-a1c9-e71a8c306ba6)

**Comment by slashtechno** [comment]
> ![Screenshot_2023-08-14-05-24-43-314_org triple banana](https://github.com/slashtechno/cloudflare-gateway-adblocking/assets/29990924/250195c6-5a79-4635-ab85-2740396bbce6)
> This token works when I use your tool

It also needs write/edit access to the scopes listed in the README

**Comment by slashtechno** [comment]
This is my token configuration:  
![Screenshot_20230813-182556.png](https://github.com/slashtechno/cloudflare-gateway-adblocking/assets/77907286/117b67ec-ac8e-42db-821b-c1cf17cfcb36)

**Comment by manhduonghn** [comment]
I set permissions like that but it said
![IMG_20230814_054451](https://github.com/slashtechno/cloudflare-gateway-adblocking/assets/29990924/31dba862-7ea7-4aee-abda-66d8cd21f9ca)

**Comment by slashtechno** [comment]
> I set permissions like that but it said
> ![IMG_20230814_054451](https://github.com/slashtechno/cloudflare-gateway-adblocking/assets/29990924/31dba862-7ea7-4aee-abda-66d8cd21f9ca)
> 

Try deleting the policies and re-run. **Make sure the hosts file you specified is not empty**

**Comment by manhduonghn** [comment]
Yeah, I will test it

**Comment by manhduonghn** [comment]
> 
![Screenshot_2023-08-14-08-06-25-394_org triple banana](https://github.com/slashtechno/cloudflare-gateway-adblocking/assets/29990924/445d3bde-7cac-4b7b-9baa-2ca654e29ae6)
Still failure

**Comment by manhduonghn** [comment]
![Screenshot_2023-08-14-08-37-51-063_com alif ide python](https://github.com/slashtechno/cloudflare-gateway-adblocking/assets/29990924/4a0b9649-1bc6-4d56-9f97-368feab6c8ff)
Now I have this problem

**Comment by manhduonghn** [comment]
![IMG_20230814_203339](https://github.com/slashtechno/cloudflare-gateway-adblocking/assets/29990924/41d089ef-b778-4e0c-9f22-cc6cb18696f1)
Success, thanks so much

**Comment by slashtechno** [comment]
> ![IMG_20230814_203339](https://github.com/slashtechno/cloudflare-gateway-adblocking/assets/29990924/41d089ef-b778-4e0c-9f22-cc6cb18696f1)
> Success, thanks so much 

No problem, glad it's working now.

**Comment by manhduonghn** [comment]
But when I try Steven Black list. It failed 
![Screenshot_2023-08-14-20-48-45-959_com termux](https://github.com/slashtechno/cloudflare-gateway-adblocking/assets/29990924/783d1423-606b-4725-888f-3998f99de36d)

**Comment by slashtechno** [comment]
I think this has to do with a connection error. Try deleting and re-running it. I think that fixed it for me when I encountered a similar error.

**Comment by manhduonghn** [comment]
I will try

**Comment by manhduonghn** [comment]
> I think this has to do with a connection error. Try deleting and re-running it. I think that fixed it for me when I encountered a similar error.

It's true

**Comment by manhduonghn** [comment]
I use this by Github Action. It's easier

**Comment by manhduonghn** [comment]
![Screenshot_2023-08-15-23-52-11-124_com kiwibrowser browser](https://github.com/slashtechno/cloudflare-gateway-adblocking/assets/29990924/50f3d871-9557-4664-8af1-a96fea7d396a)

**Comment by manhduonghn** [comment]
I make [this](https://github.com/luxysiv/Cloudflare-Gateway-Pihole) to use Github Action run your code and easier on Termux
